name: shimmer_premium
description: "A lightweight and Highly customizable Flutter package to add shimmer effects as loading placeholders"
version: 0.0.1
repository: "https://github.com/jbjason/shimmer_premium/tree/main"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik_Regular
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf

    - family: Rubik_Medium
      fonts:
        - asset: assets/fonts/rubik/Rubik-Medium.ttf

    - family: Rubik_Bold
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf

    - family: Rubik_Black
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf

    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

    - family: Poppins_Black
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
